input:
  inproc: "dimo_cloudevents"

buffer:
  memory:
    limit: 10485760
    batch_policy:
      enabled: true
      count: 5000
      period: "5s"

pipeline:
  processors:
    - label: "convert_cloudevent_to_parquet"
      dimo_raw_parquet:
        prefix: "cloudevent/valid/"

output:
  label: "insert_valid_cloudevent"
  fallback:
    - broker:
        pattern: fan_out_sequential_fail_fast
        outputs:
          # First: write parquet to S3
          - fallback:
              - label: "insert_valid_cloudevent_parquet_s3"
                switch:
                  cases:
                    - check: 'metadata("dimo_s3_upload_key").or("") != ""'
                      output:
                        aws_s3:
                          bucket: "${PARQUET_BUCKET}"
                          region: "${S3_AWS_REGION}"
                          content_type: application/octet-stream
                          path: ${!metadata("dimo_s3_upload_key")}
                          credentials:
                            id: "${S3_AWS_ACCESS_KEY_ID}"
                            secret: "${S3_AWS_SECRET_ACCESS_KEY}"
                    - check: ''
                      output:
                        drop: {}
              - label: "s3_parquet_failure"
                drop: {}
                processors:
                  - label: "insert_valid_cloudevent_parquet_s3_failure"
                    log:
                      level: ERROR
                      message: 'failed to store parquet file: ${!metadata("fallback_error").or("unknown")}'
    - drop: {}
